### ISSUE TITLE
calc_w function issue

### ISSUE THREAD

**Issue by oooook0** [LasseRegin/SVM-w-SMO#3]
Hey Lasse,

When I tried your SVM, it seems calc_w was not working properly as `alpha*y` calculated the dot product of these two vectors so that your function doesn't really return the right `w`. I replace your function with mine below, which works. Let me know what you think, I can do a pull request to correct it.

```python
    def calc_w(self, alpha, y, X):

        new = np.multiply(alpha,y)
        return np.dot(X.T, new)
```

Yitao

**Comment by LasseRegin** [comment]
Hi Yitao,

Thanks for noticing! Feel free to open a pull request.

/Lasse

**Comment by oooook0** [comment]
Hey Lasse,

Do you mind giving me edit access to your repo so that I can open a new branch and open a pull request.

Yitao

**Comment by oooook0** [comment]
Hey Lasse,

The pull request has been created, please take a look. 

Yitao
